### ISSUE TITLE
Some detailed questiones about paper

### ISSUE THREAD

**Issue by Nyeilim** [zhangce01/HiKER-SGG#12]
Hello, I am very interested in your paper, it gave me a lot of inspiration. But I still have some questiones about the paper.
1. How does the "Hierarchical Clustering Algorithm" generate a multi-branch tree structure like Figure A1? According to the pseudocode, similiar to Huffman tree, it should be a binary tree structure?
2. Is there something wrong with the graph in Figure A2? According to equation (7), there should be no edges between two SE/SP nodes, i.e $\mathcal {E}^{SE \to SE}, \mathcal {E}^{SP \to SP}$
3. About External Resources(maybe?):

    1. Initial Predicate Confusion Matrix(mentioned at Section 3.2 and 3.7): from SGG-G2S's work, and generated by MotifNet, this is what I know. And relevant code is function `train_evaluate`
    2. Commensense Knowledge Graph(mentioned at Section 3.3): According to Figure 2, it is generated by the GB-Net using the VG, ConceptNet, WordNet as data. I wonder where the relevant code is or is it an existing work of GB-Net?
    3. VG Dataset Filtering: At P6 of paper, there's such a sentence.

        > Following previous work [75], we filter the dataset to use the most frequent 150 object classes and 50 predicate classes for experiments.
        >

        The same as above, I wonder where the relevant code is. By the way, does this paper use any of the IMP's work except VG Metadata mentioned in "README.md"? What is the "following" means? the way to filter the VG dataset?
4. At Section 3.4, there's such a sentence.

    > To initialize the scene graph for each sample, we first utilize the object detector to find potential objects. We then create a SE node for each object and a SP node for each pair of objects.
    >

    If the RoIs corresponding to two SE don't intersect, will there still be corresponding SP nodes? How does the model consider non-directly touching triplets? any other steps?
5. What exactly does the model learn during training? Is it a good representation of node(CE,CP,CXE,CXP) features in "Hierarchical Commonsense Knowledge Graph" and a good probability transfer matrix in "Adaptive Refinement"?
6. How to refine?

    In my intuition, the function of the probability transfer matrix is to convert a general predicate predicted by the model to a finegrained predicate in a similar way to table lookup. for example, the model predictes a general predicate `on`, then the program queries the matrix and finds that `on` has a 30% probability to be transformed into `standing on` and a 40% probability to be transformed into `lying on`, so the final predicted result is `lying on`.

    But I seem to have understood it wrongly. According to Figure A3, the probability transfer matrix after multiple iterations is a matrix with large weights on the diagonal, which means that the transfer of predicates is more inclined to loop, just like `on` to `on` not other finegrained predicates.

    So Where did I go wrong? I sincerely hope you can explain this part to me.

**Comment by zhangce01** [comment]
Thank you for your interests in this work! Hope the following responses can address your questions:

1. We are using `scipy.cluster.hierarchy` to generate this hierarchy. Yes, it is binary, but you can set certain thresholds to split the tree into multiple branches.
2. Thank you for your careful read of our paper. Yes, you're right; Figure A2 is not entirely accurate. We will try to revise it in future versions.
3. (i) Yes, the initial confusion matrix is taken from SGG-G2S. (ii) The commonsense knowledge graph sourced from external databases is collected by GB-Net. You can find more detailed collection process in supplementary materials of GB-Net. In this work, we extend the commonsense knowledge graph to also encode hierarchical connections as in Figure 2 and Equation (6). (iii) In Section 4 of IMP [75], they manually clean the data and use the most frequent 150 object categories and 50 predicates for evaluation. We also follow this evaluation protocol for a fair comparison. We don't have the code for the data cleaning process, and the dataset was already cleaned when the annotations/metadata were downloaded from IMP.
4. As in previous works in the field of SGG, such as IMP and GB-Net, we initialize the SP nodes using the feature of the union bounding boxes.  If two objects do not intersect, no corresponding SP node will be created.
5. Yes, exactly.
6. Your intuition is correct: that is the motivation behind SGG-G2S, which has been empirically proven effective. The purpose of our adaptive refinement is to capture subtle correlations between predicate classes that go beyond the initial transfer matrix, as indicated by smaller values off the diagonal (e.g., 'near' with 'along/and/between') in Figure A3. It’s important to note that we use a weighted linear combination in Equation (20), specifically 0.9 (transfer matrix from the last step) + 0.1 (transfer matrix from the current step). This ensures that the initial transfer matrix still plays a very important role and our adaptive refinement only minorly update it.

Please let us know if you have more questions and we would be more than happy to answer.

**Comment by Nyeilim** [comment]
thank you for answer, but I still don't understand the refinement.

further inquiry on questions 6: the matrix shown in Figure A3, is a visualization of probability transfer matrix which denoted as $\Huge \tau$ in Section 3.7? Or is a visualization of final prediction result of predicates after adaptive refinement.

**Comment by zhangce01** [comment]
It's the predicate confusion matrix evaluated on the training set at the 5th epoch, denoted as $\mathcal{R}^5$. To obtain $\mathcal{T}^5$, we need to first add an identity matrix following Equation (18) then calculate the weighted average following Equation (20).

**Comment by Nyeilim** [comment]
Thank you for your patient answer, which helps me a lot. 
I study the relevant code about refinement (my_ggnn_10.py line 408) and find that actually it is the inverse matrix of the transfer matrix used for probability transfer. In my opinion, transfer matrix can be regarded as a diagonally weighted strengthed version of the confusion matrix, so it all makes sense.😄
I am reading your code carefully recently, and I may raise some questions about the code later, especially the abbreviations of many variable names.
