### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Maritime-Moon** [zhangce01/HiKER-SGG#13]
Can you tell me what these four files contain? They are all_edges_with_sccluster2_pred_ent.pkl, emb_mtx_with_sccluster2_pred_ent.pkl, pred_counts.pkl and conf_mat_updated.npy.

**Comment by zhangce01** [comment]
The first two files contain the hierarchical knowledge graphs we created, which encode commonsense knowledge about predicates and entities. Specifically, `all_edges_with_sccluster2_pred_ent.pkl` contains 4 matrices (edges_ent2ent, edges_pred2pred, edges_ent2pred, edges_pred2ent) to indicate the commonsense connection between each pair of predicates/entities, `emb_mtx_with_sccluster2_pred_ent.pkl` contains two matrices that encode the embedding of each predicate and entity.

Besides, `pred_counts.pkl` stores the frequencies of each predicate in the training set of VG. `conf_mat_updated.npy` is the confusion matrix between predicates, which is initialized with [SGG-G2S](https://github.com/ZhuGeKongKong/SGG-G2S) ([conf_mat_freq_train.npy](https://github.com/zhangce01/HiKER-SGG/blob/main/conf_mat_freq_train.npy)), and updated during our training process. See Sec. 3.7 of our paper for more details.
