### ISSUE TITLE
apex dependency in requirement.txt is a local file?

### ISSUE THREAD

**Issue by zseda** [zhangce01/HiKER-SGG#14]
Line 3 of the requirements.txt (https://github.com/zhangce01/HiKER-SGG/blob/4bdb5f9ee2896597d9d598962c3883e3542aa127/requirements.txt#L3C1-L3C28)

> apex @ file:///home/ce/apex

This is a local dependency in your home directory?! Only thing on PyPI I can find is this https://pypi.org/project/apex/ but (1) this doesn't satisfy the dependency and (2) it is from 2013 so I doubt it is the correct package.

Can you clarify @zhangce01 ?

**Comment by zhangce01** [comment]
Yes, apex is locally installed from source. The pypi version is not the correct one. Please follow the installation instructions in https://github.com/NVIDIA/apex for more details. Thanks!
