### ISSUE TITLE
requirements.txt contains a number of packages that conflict with python3.8.10

### ISSUE THREAD

**Issue by Andy20178** [zhangce01/HiKER-SGG#15]
Thanks for your work! There are a lot of libraries that require python>=3.9, and a lot of libraries that contain conflicts. The this reduced set you gave in issue #8 is missing a lot of libraries. Can you reissue a more accurate requirements.txt? Thanks!

**Comment by zhangce01** [comment]
Hi, thank you for your interest in our work. I recommend starting with the reduced set and installing the necessary packages as indicated by the error messages. This should be relatively straightforward, with the exception of the apex package, which may be more challenging. You'll need to compile it locally by following their instructions.

Sorry for the inconvenience caused.

**Comment by Andy20178** [comment]
Thank you for your reply. There are some challenges in the rendering code of part of the weather. After my efforts, I successfully installed all the packages
