### ISSUE TITLE
Checkpoint link is broken

### ISSUE THREAD

**Issue by carloscaetano** [zhangce01/HiKER-SGG#17]
Hi, I can not download the Faster-RCNN checkpoint located at: https://www.dropbox.com/s/cfyqhskypu7tp0q/vg-24.tar?dl=0

Can you, please, provide the link?

Thanks.

**Comment by carloscaetano** [comment]
The link for the pre-trained GB-Net checkpoint vgrel-11 is also broken. Can you, please, also provide it?

**Comment by zhangce01** [comment]
Hi, I think both links should be working now. Occasionally, they may go down if too many users try to download them in a single day.

**Comment by carloscaetano** [comment]
Thanks a lot @zhangce01 ! And congratulations for the work!
