### ISSUE TITLE
Updated matrix

### ISSUE THREAD

**Issue by carloscaetano** [zhangce01/HiKER-SGG#18]
Hi, could you please provide the  'conf/conf_mat_updated_8.npy' used in the evaluation scripts? I saw that they got updated in the training notebooks, but I am encountering problems with apex in my system and could not run the training. Since you provided the weights/checkpoints already, could you please provide the updated matrix?

**Comment by zhangce01** [comment]
Hi, thank you for your interest in our work. Unfortunately, we do not retain the weights for the updated matrix. However, feel free to share the issues you're encountering with Apex, and maybe we can discuss possible solutions.
