### ISSUE TITLE
SGG on Custom images

### ISSUE THREAD

**Issue by liw1st** [zhangce01/HiKER-SGG#3]
Hello author, I would like to ask whether HiKER-SGG can generate scene graphs from custom images? Where can I get information about the generated scene graphs?

**Comment by zhangce01** [comment]
Hi, thank you for your interest in this work. Yes, HiKER-SGG can be applied to custom images. To do this, you need to train a model first and then create a custom dataloader to feed your custom data to HiKER. The output scene graphs will be available in the form of a dictionary `pred_entry`. You can then refer to [this link](https://svl.stanford.edu/projects/scene-graph/dataset/VG-SGG-dicts.json) to map the predictions to actual objects and predicates.

**Comment by carloscaetano** [comment]
@liw1st , did you manage on how to generate the scene graphs?
