### ISSUE TITLE
Specific algorithm implementation of hierarchical clustering

### ISSUE THREAD

**Issue by HWH-2019** [zhangce01/HiKER-SGG#5]
Hello author, I am very interested in your work, but I am confused about how to implement the hierarchical clustering algorithm in the paper. 
Can you provide an implementation code for reference?

**Comment by zhangce01** [comment]
Thank you for your interest in this work. We don't plan to release the code for hierarchical clustering, however, you can easily implement it using `scipy.cluster.hierarchy`. You can also refer to the pseudo-code we provided in Section A.1 of the supplementary material for more details.
