### ISSUE TITLE
Version incompatible

### ISSUE THREAD

**Issue by Maritime-Moon** [zhangce01/HiKER-SGG#8]
installing some libraries from a requirements.txt file in PyCharm's terminal

**Comment by zhangce01** [comment]
Hi, thank you for your interest in this work. In the `requirements.txt` file, I list all the packages in my environment. I recommend first installing the packages listed in [this reduced set](https://github.com/alirezazareian/gbnet/blob/master/requirements.txt). Once you have these installed, you can run the code and install any additional packages as needed, according to the specified versions in `requirements.txt`.
